### ISSUE TITLE
`aliases-prefix` setting not persistent

### ISSUE THREAD

**Issue by sebastianst** [zimfw/git#10]
The aliases prefix setting is not working properly for me (setting `g`). When I modify the file `.zimrc`, save it, and open a new terminal, the setting _is_ applied. It doesn't really matter whether I put the `zstyle` directive before or after `zmodule git`.

Now comes the weird thing. Upon opening the _next_ terminal, the setting is suddenly gone again and the prefix is `G` is used again. Now I can open `.zimrc` again, change it, save it, first terminal works, second and subsequent it's gone again.

In my `.zimrc`, I even put
```zsh
zstyle ':zim:git' aliases-prefix 'g'
zmodule git
zstyle ':zim:git' aliases-prefix 'g'
```
but again, only works on first terminal, not any subsequent.

**Comment by ericbn** [comment]
All the settings should be added to the .zshrc file (not the .zimrc). And for zstyles, they should be added in .zshrc before it sources Zim's init.zsh (which sources the modules).

We even have [this in our zshrc template](https://github.com/zimfw/install/blob/3c346360e73609f0fc2829992f79a771fc731db7/src/templates/zshrc#L51).

Maybe we should explicitly mention in the modules' README.md that the settings go to the .zshrc file.

**Comment by sebastianst** [comment]
Oh didn't see that... Thanks, that would be helpful. I intuitively put those settings into my `.zimrc`.
