### ISSUE TITLE
Option to set alternative git command, like `git-branchless wrap --`

### ISSUE THREAD

**Issue by sebastianst** [zimfw/git#15]
**Is your feature request related to a problem? Please describe.**  
I'd like to use the aliases provided by the git module with `git-branchless`. They [recommend](https://github.com/arxanas/git-branchless/wiki/Installation) setting an alias for `git` like `alias git='git-branchless wrap --'`

**Describe the solution you'd like**  
A configuration flag to set a git wrapper.

**Describe alternatives you've considered**  
None come to my mind. I think just setting `alias git='git-branchless wrap --'` wouldn't work because the `git ` all the aliases wouldn't be replaced by this, right?

**Comment by ericbn** [comment]
Hi @sebastianst. It should be file if you define `alias git='git-branchless wrap --'"` in your .zshrc file, as recommended in the documentation you mention. This module does not define an alias for `git`, and will use whatever alias is defined, if any.

> I think just setting `alias git='git-branchless wrap --'` wouldn't work because the `git ` all the aliases wouldn't be replaced by this, right?

It should work.

**Comment by sebastianst** [comment]
Thanks @ericbn didn't know that aliases are applied recursively!
