### ISSUE TITLE
Alias lookup helper

### ISSUE THREAD

**Issue by sQVe** [zimfw/git#4]
Hey :wave:,

I think it would be helpful for everyone, but especially newcomers, if we had a script/function/helper that helps the user to find the correct git alias. I've been using the following script for quite some time and it's been very helpful: https://github.com/sQVe/bin/blob/ca39b8dde7145bc2ee4b544ecbee6d4f00e9b854/lookup-git-alias.sh

This allows me to do the following:
```sh
% which ga
ga: aliased to lookup-git-alias

% ga remote
gR     git remote              manages tracked repositories.
gRl    git remote --verbose    lists remote names and their URLs.
gRa    git remote add          adds a new remote.
gRx    git remote rm           removes a remote.
gRm    git remote rename       renames a remote.
gRu    git remote update       fetches remotes updates.
gRp    git remote prune        prunes all stale remote tracking branches.
gRs    git remote show         shows information about a given remote.

% ga amend
gcf    git commit --amend --reuse-message HEAD    amends the tip of the current branch reusing the same log message as
gcF    git commit --verbose --amend               amends the tip of the current branch.
```

**Comment by ericbn** [comment]
Loved your script! I've been doing just things like `alias | grep 'git remote'` all this time, which misses the short description we have in the README.md.

It can be a Zsh function instead, so we don't need to export ZIM_HOME (which we don't in the default installation), and also not depend on GNU sed and on ripgrep. I can work on your code, if you allow me.

Not sure about the `Ga` alias for this. It could be used for git archive or for git apply in the future. Maybe `G?`?

**Comment by sQVe** [comment]
I think `G?` is pretty descriptive. `G/` could also be a possibility but I guess it makes less sense for people that doesn't use `vim`.

You have my full permission to use whatever you can from my script. :+1:

**Comment by ericbn** [comment]
Done. One relevant difference with your script is that the README one-liners are obtained for all aliases before grep'ing, so the given pattern tries to match that part too. One drawback is that it will be much slower that the original script, also because it's done in an expensive way (with cheap code).  :- )

**Comment by sQVe** [comment]
@ericbn Well done! I'll try it out later today. I'll property keep my script around for the speed and exclusion of description.
