### ISSUE TITLE
Update git submodules with tracking remote branch

### ISSUE THREAD

**Issue by triebelf** [zimfw/git#8]
Hi,
I used the alias 'gSu' `git submodule foreach git pull origin master` to update all submodules, but wasn't aware that it checks out master branch, even if .gitmodules specifies a different remote branch. A submodule can be configured to track a different branch than master, see for example [here](https://stackoverflow.com/questions/1777854/how-can-i-specify-a-branch-tag-when-adding-a-git-submodule). Following this, I suggest to change the alias to `git submodule update --remote` or similar.
Thanks
Felix

**Comment by ericbn** [comment]
Hi @triebelf. Good point! Do you know in which version of git was this command introduced? Initially, we don't want to break older but still available versions of git.

**Comment by ericbn** [comment]
I could as back as git version 1.8.3.1, and `git submodule update --remote` works there. I'll update this. Thanks for reporting it!
