### ISSUE TITLE
git-alias-lookup broken

### ISSUE THREAD

**Issue by sQVe** [zimfw/git#9]
Hey 👋🏼, 

I just updated and it seems that the use of `shift` in `git-alias-lookup` is broken. I get the following output:

```shell
% git-alias-lookup
git-alias-lookup:shift:8: shift count must be <= $#
sed: can't read /README.md: No such file or directory
sed: can't read /init.zsh: No such file or directory
```

This is due to the changes introduced in https://github.com/zimfw/git/commit/921e2d06d68a0120c6d01a17656810e95aa9bfac. @ericbn 👈🏼

**Comment by ericbn** [comment]
Hi @sQVe! 

Yeah, I've updated it so it takes the path to where the README.md and init.zsh files are as the first parameter. 

Take a look at the output of `type G\?` (assuming you're using G as the aliases prefix). Why do you want to call the function directly? Maybe the README.md can be improved for clarity.

**Comment by sQVe** [comment]
> Hi @sQVe! 
> 
> Yeah, I've updated it so it takes the path to where the README.md and init.zsh files are as the first parameter. 
> 
> Take a look at the output of `type G\?` (assuming you're using G as the aliases prefix). Why do you want to call the function directly? Maybe the README.md can be improved for clarity. 

Calling it directly has always worked flawlessly for me. I was now aware of this change when making the issue. I'll update my alias to include a path.

Maybe it could have a fallback path or at least output a how to use.

**Comment by ericbn** [comment]
@sQVe, I thought about having a default path, but we need the first positional parameter to be the path otherwise it would be too complex to figure out if the first parameter is the path or a grep pattern. A usage output sounds a good idea!
